"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 2.0

[[blocks]]
  alignment = "left"
  type = "prompt"

  [[blocks.segments]]
    type = "session"
    style = "diamond"
    background = "#906cff"
    foreground = "f8f8f2"
    leading_diamond = "\ue0b6"
    template = "{{ .UserName }}@{{ .HostName }} "

  [[blocks.segments]]
    type = "path"
    style = "powerline"
    powerline_symbol = "\ue0b0"
    foreground = "#f8f8f2"
    background = "#bd93f9"
    # template = " {{ .Path }} "
    [blocks.segments.properties]
      style = "agnoster_full"

  [[blocks.segments]]
    type = "git"
    style = "powerline"
    background = "#f1fa8c"
    foreground = "#282a36"
    powerline_symbol = "\ue0b0"
    template = " \ue725 ({{ .UpstreamIcon }}{{ .HEAD }}{{ if gt .StashCount 0 }} \uf692 {{ .StashCount }}{{ end }}) "
    [blocks.segments.properties]
      branch_icon = ""
      fetch_stash_count = true
      fetch_status = false
      fetch_upstream_icon = true
    
  [[blocks.segments]]
    type = "python"
    style = "powerline"
    powerline_symbol = "\uE0B0"
    foreground = "#100e23"
    background = "#ffb86c"
    template = " \uE235 {{ if .Venv }}{{ .Venv }}{{ end }}"
  
  [[blocks.segments]]
    type = "executiontime"
    style = "powerline"
    powerline_symbol = "\uE0B0"
    foreground = "#ffffff"
    background = "#8800dd"
    template = " <#fefefe>\ufbab</> {{ .FormattedMs }} "
    [blocks.segments.properties]
      # threshold = 500
      style = "austin"

[[blocks]]
  alignment = "left"
  newline = true
  type = "prompt"
  [[blocks.segments]]
    foreground = "lightGreen"
    style = "plain"
    template = "\u276f $:"
    type = "text"
